apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alcha-dashboard-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argoproj.io
  annotations:
    # 1. 업데이트할 이미지 목록과 alias (frontend) 정의
    # ECR 레지스트리 주소와 레포지토리 경로를 지정
    argocd-image-updater.argoproj.io/image-list: frontend=504554670497.dkr.ecr.ap-northeast-2.amazonaws.com/alcha/dashboard-frontend

    # 2. 가장 최근에 푸시된 태그를 사용하도록 설정
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build

    # 3. 유효한 태그 패턴 정의 (커밋 SHA 태그 사용)
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^[0-9a-f]{40}$

    # 4. Kustomize 이미지 태그 업데이트 위치 지정
    # Kustomization 파일 내의 'image' 섹션을 업데이트하도록 지시
    argocd-image-updater.argoproj.io/frontend.kustomize.image: 504554670497.dkr.ecr.ap-northeast-2.amazonaws.com/alcha/dashboard-frontend

spec:
  project: default

  source:
    # GitHub 저장소 설정
    repoURL: https://github.com/H-Autoever/alcha-dashboard-frontend.git
    targetRevision: HEAD

    # Kustomize 파일이 있는 경로
    path: k8s

    # Kustomize 빌더 사용 명시
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: default # 앱이 배포될 타겟 네임스페이스

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
